name: Aggregate hourly downloads triggers

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
      - ".github/workflows/deploy-function.yml"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
      - ".github/workflows/lint-test-function.yml"

jobs:
  call-lint-test:
    name: Lint test hourly downloads
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: aggregate_hourly_downloads

  call-deploy:
    name: Deploy hourly downloads
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: aggregate_hourly_downloads
