name: Aggregate hourly downloads triggers

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"

jobs:
  call-lint-test:
    name: Lint and Test
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: aggregate_hourly_downloads

  call-deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: aggregate_hourly_downloads
