name: Aggregate hourly downloads triggers
run-name: "Aggregate Hourly Downloads ${{ github.ref_name }} ${{ github.sha }}"

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/aggregate_hourly_downloads/**"
      - "terraform/aggregate_hourly_downloads/**"

permissions:
  id-token: write
  actions: write
  contents: read      

jobs:
  debug-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

  call-lint-test:
    name: Lint and Test
    needs: debug-trigger
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: aggregate_hourly_downloads

  deployment-routing:
      needs: call-lint-test
      runs-on: ubuntu-latest
  
      concurrency:
        group: deploy-${{ github.workflow }}-${{ github.ref }}
        cancel-in-progress: true
  
      steps:
        - name: Deployment Routing
          uses: arXiv/iac-public/.github/actions/service-deployment-routing@ARXIVCE-4101  
          with:
            image_tag: ${{ github.sha }}
            deploy_workflow: deploy-function.yml
            function_name: aggregate_hourly_downloads
            workload_identity_provider: ${{ vars.ARXIV_DEVELOPMENT_PROVIDER_NAME }}
            service_account: ${{ vars.ARXIV_DEVELOPMENT_SERVICE_ACCOUNT }}      

  # call-deploy:
  #   name: Deploy
  #   uses: ./.github/workflows/deploy-function.yml
  #   with:
  #     function_name: aggregate_hourly_downloads
