name: Format check and deploy cloud functions

on:
  workflow_call:
    inputs:
      function_name:
        type: string
        description: Name of the function directory (e.g. aggregate_hourly_downloads)
        required: true
      env:
        description: "Environment"
        required: true
        type: string
        default: ""
      image_tag:
        description: "Docker image tag (latest or the commit SHA)"
        required: false
        type: string
        default: "latest"
  workflow_dispatch:
    inputs:
      function_name:
        type: string
        description: Name of the function directory (e.g. aggregate_hourly_downloads)
        required: true
      env:
        description: "Environment"
        required: true
        type: string
        default: ""
      image_tag:
        description: "Docker image tag (latest or the commit SHA)"
        required: false
        type: string
        default: "latest"

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Format check
        run: terraform fmt -check
        working-directory: "terraform/${{ inputs.function_name }}"

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'development' }}
    if: github.ref == 'refs/heads/main'
    needs: format-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip function source
        # zips all files inside the 'src/' directory into src.zip
        run: |
          SOURCE_DIR="stats-functions/${{ inputs.function_name }}"
          TERRAFORM_DIR="terraform/${{ inputs.function_name }}"

          cd "$SOURCE_DIR/src"
          zip -r src.zip .

          mv src.zip "../../../$TERRAFORM_DIR/src.zip"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ inputs.PROVIDER_NAME }}
          service_account: ${{ inputs.SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check version
        run: terraform --version

      - name: Initialize remote backend
        run: terraform init -backend-config="bucket=${{ inputs.ENV_VAR }}-arxiv-terraform-state"
        working-directory: "terraform/${{ inputs.function_name }}"

      - name: Apply
        run: terraform apply -var-file=envs/${{ inputs.ENV_VAR }}.tfvars -var="commit_sha=${{ github.sha }}" -auto-approve
        working-directory: "terraform/${{ inputs.function_name }}"
