name: Hourly edge requests triggers
run-name: "Hourly Edge Requests ${{ github.ref_name }} ${{ github.sha }}"

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
      - ".github/workflows/deploy-function.yml"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
      - ".github/workflows/lint-test-function.yml"

jobs:
  call-lint-test:
    name: Lint and Test
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: hourly_edge_requests

  call-deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: hourly_edge_requests
