name: Hourly edge requests triggers

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  call-lint-test:
    name: Lint and Test
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: hourly_edge_requests

  call-deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: hourly_edge_requests
