name: Hourly edge requests triggers
run-name: "Hourly Edge Requests ${{ github.ref_name }} ${{ github.sha }}"

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  call-lint-test:
    name: Lint and Test
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: hourly_edge_requests

  deployment-routing:
    name: Deployment Routing
    needs: call-lint-test
    uses: arXiv/iac-public/.github/actions/service-deployment-routing@ARXIVCE-4101  
    with:
      image_tag: ${{ github.sha }}
      deploy_workflow: deploy-function.yml
      function_name: hourly_edge_requests
      workload_identity_provider: ${{ vars.ARXIV_DEVELOPMENT_PROVIDER_NAME }}
      service_account: ${{ vars.ARXIV_DEVELOPMENT_SERVICE_ACCOUNT }}

  # call-deploy:
  #   name: Deploy
  #   uses: ./.github/workflows/deploy-function.yml
  #   with:
  #     function_name: hourly_edge_requests
