name: Hourly edge requests triggers

on:
  push:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
      - ".github/workflows/deploy-function.yml"
  pull_request:
    branches:
      - main
    paths:
      - "stats-functions/hourly_edge_requests/**"
      - "terraform/hourly_edge_requests/**"
      - ".github/workflows/lint-test-function.yml"

concurrency:
  # cancel any existing unfinished jobs if this workflow is retriggered
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  call-lint-test:
    name: Lint test hourly edge requests
    uses: ./.github/workflows/lint-test-function.yml
    with:
      function_name: hourly_edge_requests

  call-deploy:
    name: Deploy hourly edge requests
    uses: ./.github/workflows/deploy-function.yml
    with:
      function_name: hourly_edge_requests
