name: Lint and test function

on:
  workflow_call:
    inputs:
      function_name:
        type: string
        description: The name of the function directory (e.g. aggregate_hourly_downloads)
        required: true
  workflow_dispatch:
    inputs:
      function_name:
        type: string
        description: Name of the function directory (e.g. aggregate_hourly_downloads)
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          SOURCE_DIR="stats-functions/${{ inputs.function_name }}/src"

          python -m pip install --upgrade pip
          pip install -r "$SOURCE_DIR/requirements.txt"
          pip install -r "$SOURCE_DIR/requirements-dev.txt"

      - name: Lint
        run: |
          ruff check --output-format=github stats-functions/${{ inputs.function_name }}/src

      - name: Test with pytest
        working-directory: stats-functions/${{ inputs.function_name }}
        run: |
          pytest tests/ --cov=src/ --cov-report=html --cov-fail-under=80

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload coverage report
        uses: actions/upload-pages-artifact@v3
        with:
          path: stats-functions/${{ inputs.function_name }}/htmlcov

  deploy:
    needs: lint-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
