name: Lint and test Python services

on:
  workflow_call:
    inputs:
      service_name:
        type: string
        description: The name of the service directory (e.g. stats_api)
        required: true
  workflow_dispatch:
    inputs:
      service_name:
        type: string
        description: Name of the service directory (e.g. stats_api)
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "stats-api/pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --directory stats-api --locked --all-extras --dev

      - name: Lint
        run: |
          uv run --directory stats-api ruff check --output-format=github .

      - name: Run tests
        run: uv run --directory stats-api pytest tests
